CREATE DEFINER=`root`@`%` PROCEDURE `abrashin_HW`()
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT 'Hello world'
BEGIN
	SELECT 'Hello, World!' AS Message;
END

DELIMITER //
CREATE FUNCTION abrashin_HW2()
RETURNS VARCHAR(20)
BEGIN
	RETURN 'hello world';
END
//